# Site settings
title: "Pownas a.k.a. Jonas Arvidsons CV"
description: "Mitt (@pownas) CV för mina arbetslivserfarenheter och sociala sidor."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "@Pownas"
resume_full_name:               "Jonas Arvidson"
resume_title:                   "Utvecklare"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "pownas@outlook.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+46 (0)73-506 65 98"
resume_contact_address:         "Örebro, Sweden"

resume_header_contact_info:     "Örebro, Sweden • +46 (0)73-506 65 98 • pownas@outlook.com"
display_header_contact_info:    "true"

#resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"
resume_header_intro: "Mitt CV för mina arbetslivserfarenheter och sociala sidor. <span class=""print-only""><br /></span> Hoppas vi får arbeta tillsammans framöver!"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true
# they have to look like this, to not be shown:
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:              "https://github.com/pownas"
  resume_twitter_url:             "https://twitter.com/pownas"
  # resume_dribbble_url:          "insert Dribbble URL here"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:            "https://www.linkedin.com/in/JonasArvidson"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_youtube_url:             "https://www.youtube.com/channel/UCHbDLlJEZ_PRJADbNZiR_2A"
  resume_youtube_channel_name:    "Pownas lär dig"
  resume_website_url:             "https://jonas.arvidsonfoto.se"
  # resume_medium_url:            "https://medium.com/@username"
resume_print_social_links:        true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
